version: "3.1"
services:
  http-client:
    container_name: http_client
    image: ankhafizov/http_client:v1.0
    restart: always
    ports:
      - "80:5000"
    environment:
      - LAYER_SEGMENTATOR_HOST=layers-segmentation
      - BACKGROUND_SEGMENTATOR_HOST=sample-segmentation
      - HOST=0.0.0.0

  sample-segmentation:
    container_name: sample_segmentation
    image: ankhafizov/sample_segmentation:v1.0
    restart: always
    volumes:
      - ./CNN_weights:/usr/src/CNN_weights
    ports:
      - "5001:5001"

  layers-segmentation:
    container_name: layers_segmentation
    image: ankhafizov/layers_segmentation:v1.0
    restart: always
    volumes:
      - ./CNN_weights:/usr/src/CNN_weights
    ports:
      - "5002:5002"