version: "3.1"
services:
  sample-segmentation:
    container_name: sample_segmentation
    image: sample_segmentation
    build: ./sample_segmentation
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ../CNN_weights:/usr/src/CNN_weights
  layer-segmentation:
    container_name: layers_segmentation
    image: layers_segmentation
    build: ./sample_segmentation
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - ../CNN_weights:/usr/src/CNN_weights
  http_client:
    container_name: http_client
    image: http_client
    build: ./http_client
    restart: always
    ports:
      - "5000:5000"
