version: "3.1"
services:
  http-client:
    container_name: http_client
    image: http_client
    build: ./http_client
    restart: always
    ports:
      - "5000:5000"
    environment:
      - LAYER_SEGMENTATOR_HOST=layers-segmentation
      - BACKGROUND_SEGMENTATOR_HOST=sample-segmentation
      - HOST=ec2-54-160-137-40.compute-1.amazonaws.com

  sample-segmentation:
    container_name: sample_segmentation
    image: ankhafizov/sample_segmentation:v1.0
    restart: always
    volumes:
      - ./CNN_weights:/usr/src/CNN_weights
    ports:
      - "5001:5001"

  layers-segmentation:
    container_name: layers_segmentation
    image: ankhafizov/layers_segmentation:v1.0
    restart: always
    volumes:
      - ./CNN_weights:/usr/src/CNN_weights
    ports:
      - "5002:5002"