version: "3.1"
services:
  http-client:
    container_name: http_client
    image: ankhafizov/http_client:v1.1
    restart: always
    build: ./http_client
    ports:
      - "5000:5000"
    environment:
      - LAYER_SEGMENTATOR_HOST=layers-segmentation
      - BACKGROUND_SEGMENTATOR_HOST=sample-segmentation
      - HOST=0.0.0.0

  sample-segmentation:
    container_name: sample_segmentation
    image: ankhafizov/sample_segmentation:v1.1
    restart: always
    build: ./sample_segmentation
    volumes:
      - ./CNN_weights:/usr/src/CNN_weights
    expose:
      - "5001"
    environment:
      - LOGS_DISABLED=False

  layers-segmentation:
    container_name: layers_segmentation
    image: ankhafizov/layers_segmentation:v1.1
    restart: always
    build: ./layers_segmentation
    volumes:
      - ./CNN_weights:/usr/src/CNN_weights
    expose:
      - "5002"
    environment:
      - LOGS_DISABLED=False